#!/usr/bin/env bash

CONFIG_FILES=(
  '(./configs/fish/config.fish ~/.config/fish/)'
  '(./configs/fish/functions/fish_prompt.fish ~/.config/fish/functions/)'
  '(./configs/vim/.vimrc ~/)'
  '(./configs/vim/UltiSnips ~/.vim)'
  '(./configs/vim/words ~/.vim)'
  '(./configs/git/.gitconfig ~/)'
  '(./configs/git/ignore ~/.config/git/)'
  '(./configs/brew/Brewfile ~/.config/brewfile/)'
  '(./configs/tmux/.tmux.conf ~/)'
  '(./bin ~/)'
  '(./configs/lazygit/config.yml "~/Library/Application\ Support/lazygit/")'
  '(./configs/atuin/config.toml ~/.config/atuin/)'
  '(./configs/asdf/ruby/.default-gems ~/)'
  '(./configs/asdf/nodejs/.default-npm-packages ~/)'
  '(./configs/asdf/.asdfrc ~/)'
)

echo_header() {
  echo $1
  echo '----------------------------------------'
}

install_scripts() {
  echo_header 'Applying config'

  for entry in "${CONFIG_FILES[@]}"
  do
    eval paths=$entry
    echo Copying \"${paths[0]}\" to \"${paths[1]}\"
    mkdir -p ${paths[1]} && cp -R ${paths[0]} ${paths[1]}
  done
}

pull_changes() {
  echo_header 'Pulling changes from remote'

  git pull --rebase
}

brew_init() {
  if [ -z $(which brew) ]; then
    echo "No brew installed"
    exit 1
  fi

  brew install rcmdnk/file/brew-file
  HOMEBREW_BREWFILE=~/.config/brewfile/Brewfile brew file install
}

install_vim_dependencies() {
  read -p "Are you sure? [y/N] " -n 1 -r

  if [[ ! $REPLY =~ ^[Yy]$ ]]
  then
    exit 0
  fi

  echo
  echo 'Install vim-plug'
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  echo 'Install deno 🦖'
  asdf plugin-add deno https://github.com/asdf-community/asdf-deno.git
  asdf install deno latest

  echo 'Set up global deno'
  asdf global deno latest

  echo 'Install rust 🦀'
  asdf plugin-add rust
  asdf install rust latest

  echo 'Set up global rust'
  asdf global rust latest

  echo 'Install mocword'
  cargo install mocword
  asdf reshim rust
}

set_up_dev_env() {
  echo 'Install ruby 💎'
  asdf plugin-add ruby
  asdf install ruby latest

  echo 'Set up global ruby'
  asdf global ruby latest

  echo 'Install nodejs'
  asdf plugin-add nodejs
  asdf install nodejs latest

  echo 'Set up global nodejs'
  asdf global nodejs latest
}

case $1 in
install)
  install_scripts;;
update)
  pull_changes
  echo '\n'
  install_scripts;;
brew)
  brew_init;;
vim_dependencies)
  install_vim_dependencies;;
dev_env)
  set_up_dev_env;;
*)
  echo """
  Usage:
    scripts/run [command]

    Command:
      - install - apply configs
      - update - pull changes and apply configs
      - brew - runs brew init (requires installation before)
      - vim_dependencies - installs vim dependencies
      - dev_env - set up dev env
  """;;
esac
